"""create word_book and user_word_book tables

Revision ID: a1b2c3d4e5f6
Revises: 56a75e93f4b3
Create Date: 2026-05-14 22:30:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a1b2c3d4e5f6'
down_revision: Union[str, None] = '56a75e93f4b3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('word_book',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('word_count', sa.Integer(), nullable=False),
    sa.Column('cover_image', sa.String(length=255), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('is_free', sa.SmallInteger(), nullable=False),
    sa.Column('status', sa.SmallInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('word_book', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_word_book_category'), ['category'], unique=False)
        batch_op.create_index(batch_op.f('ix_word_book_status'), ['status'], unique=False)

    op.create_table('user_word_book',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('book_id', sa.Integer(), nullable=False),
    sa.Column('current_index', sa.Integer(), nullable=False),
    sa.Column('learned_count', sa.Integer(), nullable=False),
    sa.Column('mastered_count', sa.Integer(), nullable=False),
    sa.Column('is_current', sa.SmallInteger(), nullable=False),
    sa.Column('status', sa.SmallInteger(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['book_id'], ['word_book.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'book_id', name='uk_user_book')
    )
    with op.batch_alter_table('user_word_book', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_word_book_book_id'), ['book_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_word_book_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_word_book', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_word_book_user_id'))
        batch_op.drop_index(batch_op.f('ix_user_word_book_book_id'))

    op.drop_table('user_word_book')
    with op.batch_alter_table('word_book', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_word_book_status'))
        batch_op.drop_index(batch_op.f('ix_word_book_category'))

    op.drop_table('word_book')
    # ### end Alembic commands ###
